git:
  submodules: false # Não acompanhe os submodulos - No nosso caso não temos submodulos
  quiet: true # Faça sileciosamente para não produzir de maneira detalhada
  depth: 3 # Quando fizer o checkout, use uma profundidade de clonagem de 3. Obtenha as últimas confirmações
language: python
cache: pip # Guardando em cache os pacotes baixados pelo pip
jobs:
  include:
    - name: "Testando Python 3.8.0 no Ubuntu Xenial"
      python: 3.8

    - name: "Testando Python 3.8.0 no Ubuntu Bionic"
      python: 3.8
      dist: bionic

    - name: "Testando Python 3.7.4 no Ubuntu Xenial"
      python: 3.7.4

    - name: "Testando Python 3.7.4 no Ubuntu Bionic"
      python: 3.7.4
      dist: bionic

    - name: "Testando Python 3.8-dev no Ubuntu Xenial"
      python: 3.8-dev

    - name: "Testando Python 3.7.4 no MacOS"
      os: osx
      osx_image: xcode11.2
      language: shell

    - name: "Testando Python 3.8 no Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

  allow_failures:
    - python: 3.8-dev
    - python: 3.7.4

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - python3 -m pytest -v || python -m pytest -v