language: python
jobs:
  include:
    - name: "Testando Python 3.8.0 no Ubuntu Xenial"
      python: 3.8

    - name: "Testando Python 3.8.0 no Ubuntu Bionic"
      python: 3.8
      dist: bionic

    - name: "Testando Python 3.7.4 no Ubuntu Xenial"
      python: 3.7.4

    - name: "Testando Python 3.8-dev no Ubuntu Xenial"
      python: 3.8-dev

    - name: "Testando Python 3.7.4 no MacOS"
      os: osx
      osx_image: xcode11.2
      language: shell

    - name: "Testando Python 3.8 no Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

  allow_failures:
    - python: 3.8-dev

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - python3 -m pytest -v || python -m pytest -v